name: Integration Continue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run TypeScript type check
        run: yarn type-check

  build-image:
    runs-on: ubuntu-latest
    needs: ["test"]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE=ghcr.io/nepta75/livora-hub

          docker build . \
            --progress=plain \
            --tag $IMAGE:sha-$SHA

          docker push $IMAGE:sha-$SHA

      - name: Tag and push :preprod
        run: |
          SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE=ghcr.io/nepta75/livora-hub
          docker tag $IMAGE:sha-$SHA $IMAGE:preprod
          docker push $IMAGE:preprod

      - name: Deploy to preprod VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "docker service update --image ghcr.io/nepta75/livora-hub:preprod --with-registry-auth --detach=false livora_hub"
